config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :posts do
    resources :comments, only: [ :create ]
    resources :likes, only: [ :create, :destroy ]  # Adicionando a rota para 'likes'
  end


  resources :rooms do
    resources :chats
  end

  get "/rooms", to: "rooms#destroy"


  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "rooms#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :content, presence: true, length: {minimum: 1}  




  after_create_commit do 
    broadcast_append_to "updatechat",
    target: "updatechat"
  end
  # depois de criar um chat novo no banco de dados. atualiza sem atualizar a página onde tem <%= turbo_stream_from "updatechat" %> no id updatechat

  
  
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :users
  has_many :chats
  has_many :room_users

  validates :name, presence: true, length: {minimum: 3}


  

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :login, presence: true, uniqueness: true




  
  has_many :chats, dependent: :destroy
  belongs_to :room, optional: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    # Permite o campo 'login' no registro e na atualização do usuário
    devise_parameter_sanitizer.permit(:sign_up, keys: [ :login ])
    devise_parameter_sanitizer.permit(:account_update, keys: [ :login ])
  end


  def after_sign_out_path_for(resource_or_scope)
    new_user_session_path # Redireciona para a página de login
  end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
   include ActionView::RecordIdentifier
  # isso aqui faz vc conseguir usar o dom_id ali no Turbo.StreamsChannel
  def create
    @room = Room.find(params[:room_id])
    @chat = @room.chats.build(chat_params)
    @chat.user_id = current_user.id
    @chat.save
  end




  private


  def chat_params
    params.require(:chat).permit(:content)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController 
  before_action :authenticate_user!
  include ActionView::RecordIdentifier



  def index
    @rooms = Room.all
  end


  def create 
    @room = Room.new(room_params)
    if @room.save
      redirect_to rooms_path, notice: "created"
    else 
      render :new, notices: "fail to create room"
    end
  end




  def show
    @room = Room.find(params[:id])
    user = current_user
    @room.users << user
    

    Turbo::StreamsChannel.broadcast_update_to "updateusername",
    target: dom_id(@room),
    partial: "rooms/room",
    locals: { room: @room }
    

    others_rooms = Room.where.not(id: @room.id)
    if others_rooms
      others_rooms.each do | room | 
        room.users.delete(user) 
        Turbo::StreamsChannel.broadcast_replace_later_to "updatecountuser",  
        target: dom_id(room, :index),
        partial: "rooms/countuser",
        locals: { room: room }
      end
    end
    Turbo::StreamsChannel.broadcast_replace_to "updatecountuser", 
    target: dom_id(@room, :index), 
    partial: "rooms/countuser", 
    locals: { room: @room }

    render layout: false if turbo_frame_request?
    # basicamente ta dizendo que se tem um turbo frame sendo chamado na def show, não é pra renderizar o layout normal. No caso ele vai renderizar só o que o turbo-frame chama. 
    @chat = Chat.new 
  end



  def new
    @room = Room.new
  end


  def destroy
    @room = Room.find(params[:id])
    Turbo::StreamsChannel.broadcast_replace_later_to "updatecountuser",
    target: dom_id(@room, :index),
    # colocar um :index ali, faz botar um index do id, para nao ficar igual ao updateusername e dar bug. No caso ficaria assim o id da div "index_room_31".
    # se colocasse ali :count, o id da div ficaria "count_room_31"
    partial: "rooms/countuser",
    locals: {room: @room}



    @user = current_user
    @room.users.delete(@user)
    Turbo::StreamsChannel.broadcast_remove_to "updateusername",
    target: dom_id(@user),
    partial: "rooms/room",
    locals: { room: @room }
    redirect_to rooms_path, notice: "destroy"
  end

  private


  def room_params
    params.require(:room).permit(:name)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/chats/_chat.html.erb

<div id="<%= dom_id(chat) %>" class="user-anwser"  userlogged="<%= chat.user.login %>"  style="display: flex; margin-top: 20px; margin-bottom: 20px; gap: 5px;align-items: center;"> 
  <p style="color: #ffffff;font-size: 14px"><strong><%= chat.user.login %>:</strong></p>
  <div >
    <p  style="color: #ffffff;font-size: 12px"><%= chat.content %></p>
  </div>
</div>


app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Blog" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= javascript_importmap_tags %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload"  %>



  </head>

  <body>
    
    <main class="container mx-auto mt-28 px-5 flex">
      <div class="main-container" style="display: flex;background-color: #ffffff ">
        <% if user_signed_in? %>
          <%= render "shared/side_bar" %>
        <% end %>
        <%= yield %>
      </div>
    </main>
  </body>
</html>

app/views/rooms/_countuser.html.erb
<div id="<%= dom_id(room, :index) %>">
   <div style="display: flex; align-items: self-end; gap: 2px;padding-left: 3px">
        <% if room.users.count > 0 %>
            <%= image_tag("/images/onlineicon.png", alt: "icon", style: "margin-bottom: 1px;", class: "icon-online-offline")%>
        <% else %>
            <%= image_tag("/images/offlineicon.png", alt: "icon", style: "width: 15px !important;" , class: "icon-online-offline")%>
        <% end %>
        <p class="users-online"> <%= room.users.count %> users online </p>
    </div>
</div>

app/views/rooms/_room.html.erb
<div id="<%= dom_id(room) %>">
  <% room.users.each do |user| %>
    <div>
      <p style="color: #ffffff " class="user-email"><%= user.email %></p>
    </div>  
  <% end %>
</div>

app/views/rooms/index.html.erb
<div class="rooms-home-page-container" data-controller="log-button">
  <% if user_signed_in? %>
    <div class="user">
      <p style="text-decoration: underline"><%= current_user.login %></p>
      <%= button_to  image_tag("/images/logout.png", alt: "Icon", class: "img-logout"), destroy_user_session_path, method: :delete, class: "btn-logout", style: "background: none; border: none; cursor: pointer" %>
    </div>
  <% end %>
    <h5>Rooms</h5>
    <div class="rooms-home-page">
      <div>
        <%= turbo_stream_from "updatecountuser" %>
        <div class="room-box-container">
          <% @rooms.each do | room | %>
              <div class="room-box">
                <div>
                  <%= render "rooms/countuser", room: room %>
                </div>
                <div class="link-room"  >
                  <%= link_to room.name, room_path(room),  data: {turbo_frame: "room_chat", "log-button-target": "openchat",  action: "click->log-button#openChat"} %><br>
                  <%# aqui ta chamando data: {turbo_frame: "qualquer nome"} %>
                </div>
              </div>
          <% end %>
        </div>
      </div>
      <div class="chat-open">
        <turbo-frame id="room_chat">
          
        </turbo-frame>
        <%# aqui precisa chamar aonde tu quer renderizar o turbo-frame com o mesmo id que passou ali em cima %>
        <%# e dai tu bota de novo esse turbo-frame id="room_chat" em volta do que tu quer que renderize aqui, no caso estou chamando isso na view show %>
      </div>
    </div>
</div>



app/views/rooms/new.html.erb
<div class="new-page">
<h3>Create a room </h3>
<%= form_with model: @room, url: rooms_path, method: :post, local: true do | form | %>
    <div class="new-page-form">
        <div>
        <%= form.label "Name of the room" %>
        </div>
        <div>
        <%= form.text_field :name %>
        <%= form.submit "Create" %> 
        </div>
    </div>
<% end %>
</div>

app/views/rooms/show.html.erb


<%# tudo que estiver dentro desse turbo-frame room_chat vai ser chamado e renderizado la na view index %>
<turbo-frame id="room_chat">
<%= turbo_stream_from "updateusername" %>

<div class="chat-open-container" >
  <div class="back-to-rooms-container">
    <%= render "rooms/room", room: @room %>
    <%= button_to room_path(@room), method: :delete, data: { confirm: 'Tem certeza que quer sair da sala?',   action: "click->log-button#closeChat" } , style: "background: none; border: none; cursor: pointer" ,form_class: "logout-form" do %>
      <%= image_tag('/images/cross.png', alt: 'Logout', width: '20px') %>
    <% end %>  
  </div>


  <%# o <%= turbo_stream_from "updatechat" pecisa esta sempe antes do id que tu colocou no caso aqui de baixo  id="updatechat" %>
  <div data-controller="log-button"     data-log-button-current-user-value="<%= current_user.login %>" >
    <%= turbo_stream_from "updatechat" %>
    <div id="updatechat"      >
      <% @room.chats.each do |chat| %>
        <%= render "chats/chat",  chat: chat %>
      <% end %>
    </div>


    <%= form_with model: [@room, Chat.new] do | form | %> 
    <div class="form-input-open-chat">
        <%=form.text_field :content , style: "width: 90%;height: 30px;border-radius: 6px;border: none;", class: "input-text-message", data: {"log-button-target": "input" }  %>
        <%= submit_tag '', src: "images/send.png", type: 'image', alt: 'Send', width: '30px', data: {action: "click->log-button#scrollToBottom"}  %>
    </div>
    <% end %> 
    <%# mesma coisa que fazer def new
      @room = Room.find(params[:room_id])
      @chat = @room.chats.new
    end no controller %> 
  </div>

</div>


</turbo-frame>


app/views/shared/_side_bar.html.erb
<div class="side-bar-container">
    <div class="side-bar">
        <%= link_to image_tag("/images/house.png", alt: "Icon", class: "img") , rooms_path%>
        <%= link_to image_tag("/images/chat.png", alt: "Icon", class: "img"), new_room_path%>
    </div>
</div>